# This file is for production overrides of any configuration
# in the _data/site_config.yml file.
environment: production
remote_data_prefix: "https://sdgs-nepal.github.io/prod-data"
analytics:
  ga_prod: ''
